### ISSUE TITLE
Keyboard gets stuck up after sending a message

### ISSUE THREAD

**Issue by SuperDisk** [signalapp/Signal-iOS#1531]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
When you send a message in a chat, the keyboard gets stuck in the "up" position. Previously you could "scroll" your finger down over the keyboard and it would push it down and hide it. You can see this in action in iMessage. You can fix this by going back to the chats list, then reopening the chat. The bug appeared in the same update that included switching back to the default keyboard after using a 3rd party one, so I think this is probably a side effect of that.

### Steps to reproduce
- Open a chat
- Send a message
- Try to pull the keyboard down and hide it

**Actual result:** The keyboard stays up and won't go away.
**Expected result:** The keyboard would slide down and hide itself.

### Screenshots

![2016-12-07 20 05 26](https://cloud.githubusercontent.com/assets/1688837/20993538/f89dd856-bcb8-11e6-8d8e-02f95a151edb.png)

My thumb is dragging down over the keyboard in this pic.

### Device info

**Device**: iPhone 6S
**iOS version**: 10.2 (14C89)
**Signal version:** 2.6.7

### Link to debug log

https://gist.github.com/7c85d72c733f7144735ed76fb57bc121

**Comment by jaredStef** [comment]
I've got a PR ready to fix this. One line fix. I just add a call to 
> [self.view endEditing: YES]; 
when the didPressSendButton method is called in the MessagesViewController. 
Could someone give me the ok before I submit it?

**Comment by michaelkirk** [comment]
Hmm... I'm not immediately able to reproduce this.

@jaredStef - Without the actual context I'm not sure that's the right fix. To be clear we don't want to dismiss the keyboard *every* time a message is sent, but the user *should* be able to swipe down to dismiss it after sending, same as before.

**Comment by jaredStef** [comment]
True. I can reproduce sometimes, but not consistently.

**Comment by SuperDisk** [comment]
I can reproduce the issue 100% of the time. Are you also running the iOS prerelease Jared?

**Comment by michaelkirk** [comment]
Sorry to be super pedantic, I promise I'm only asking because I'm trying to fix it. =)

> I can reproduce the issue 100% of the time.

Do you mean that after sending a message you can *never* swipe the keyboard down?

Or do you mean that after sending enough messages, eventually, you can get the app into a state where you can't swipe the keyboard down.

**Comment by SuperDisk** [comment]
After sending a single message, the keyboard becomes permanently stuck in the up position. When you return to the list of open conversations and then go back in, the keyboard works fine (will go up and down) until you send another message. I've gotten in the habit of "pulling" the left side slightly after sending every message to trigger the keyboard reset.

**Comment by SuperDisk** [comment]
This bug is fixed with the latest update.

**Comment by michaelkirk** [comment]
I have no idea how it would have been fixed.

Please let me know if it recurs.

**Comment by SuperDisk** [comment]
Ah, sorry, false alarm. It was only working for a little bit and I see that it's back to broken again.

**Comment by michaelkirk** [comment]
To be clear, the gesture is intended to be done at the top or just above the keyboard, then when you swipe you come across the keyboard.

It’s intended to be pretty similar to how it works in the native messaging app.

**Comment by SuperDisk** [comment]
Yep. I can confirm that it is in fact a bug and is still present.

**Comment by porter707** [comment]
Have the same issue.

If you open a chat and the keyboard then swipe down it works as expected. But if you send a single message and then try to swipe down it does not work, the keyboard becomes stuck.

Device info

Device: iPhone 7
iOS version: 10.3 (14E277)
Signal version: 2.10.0

**Comment by jeffpc** [comment]
Sending a message first is necessary to reproduce this - iPhone 5s, 10.3.1, 2.10.1.

**Comment by wmiaw** [comment]
I was able to get the keyboard to go back down, after getting stuck in the up position, by triggering the voice entry but immediately cancelling it.

**Comment by michaelkirk** [comment]
This is fixed in 2.19.5
