### ISSUE TITLE
Pasting a png into a chat doesn't render inline

### ISSUE THREAD

**Issue by tomk2** [signalapp/Signal-iOS#3654]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Images that are pasted from some apps do not render inline. 
Copying and pasting an image from Safari works
Copying and pasting an image from Photos works
Copying and pasting an image from Tumblr app does not work (used to work before Signal app was updated)
Today I update iOS to 11.4 and all apps (versions below) and it stopped working

### Steps to reproduce
-Copied an image (png) from a different app (eg. Tumblr 11.1.1) 
-Opened Signal app and navigated to a conversation
-Long-pressed in New Message textbox until Paste showed up
-Tapped on Paste 
-Picture preview popped up with correct image
-Tapped Send

**Actual result:** 
Message is sent as file attachment (filename and extension are visible including file size) 
Same result whether text is added or not in preview before sending

**Expected result:** 
(Worked in previous version) preview of image is visible in chat

### Screenshots

![img_7002 jpg](https://user-images.githubusercontent.com/3288775/42297518-dd3d0ee0-7fb4-11e8-8805-6a5b09d1c10b.jpg)

### Device info
**Device**: iPhone 6s Plus

**iOS version**: 11.4 (15F79)

**Signal version:** 2.27.0.7

### Link to debug log
https://debuglogs.org/d21b2f75b1455e53fe96f69d3cf1bb9f5d7b1fdbfb989e76eae4552a7ad068fb.zip

**Comment by michaelkirk-signal** [comment]
I was not able to reproduce this behavior.

Can you provide a problematic PNG?

**Comment by pleasantone** [comment]
Reproduced with iOS 12.1b2 in conversation with an Android device (unknown version). Android user sent me a series of .png that also do not display inline.

Save to photo is an option, so I have to save them out, which violates security containment principles.

Can provide .png if required for further debugging.

Happy to help.

**Comment by tzs1** [comment]
I had the same issue. Copied an image from the web and pasted into a conversation didn’t render the picture.

**Comment by mrgtreeskier** [comment]
Sending a .jpeg from Android to iOS is causing this problem too. iOS to Android does not replicate the problem. Android to Android does not replicate.

Videos render within the iOS environment. It seems like it's only pictures.

Debug log from Android: https://debuglogs.org/28cca2f371dcbe5e60ff911b904f30fc55f8ce992f537039c53dcd6cc77d11a2

Debug log from iOS:
https://debuglogs.org/04629372e509f99354d56b710521eb9a2749fb1e6c17a53b0c1963525d8b79b1.zip

Screenshots:
![fullsizeoutput_1201](https://user-images.githubusercontent.com/11836366/44996929-bd336b00-af78-11e8-813f-53a3db987a40.jpeg)

**Comment by dgobaud** [comment]
same problem :( upgraded to iOS 11, took screenshot, sent via + icon then -> Photo Library and it doesn't render :( iOS 10 I think used JPGs for screenshots and everything worked but now using PNGs and they don't show up on mobile iOS but do in desktop :(

**Comment by robwilkes** [comment]
I have this issue as well, really easy to reproduce.

Attempt 1:
Open Mail app, take a screenshot (on iPhone X, Volume Up + Power).
Open Signal, inside a chat, select +, select Photo Library, select the screenshot you just took.
It will attach as a PNG, not an image.

Attempt 2:
Open Photos app, browse to screenshot, tap the share with icon, select Signal, sent to chat.
It will attach as a JPEG, not an image.

This occurs with at least the Mail app, unsure about other apps or image sources.

Interestingly, if I take a screenshot of the home screen, that's inserted as an inline image fine, so it's not ALL screenshots/images.

**Comment by FriedCircuits** [comment]
I have the same issue happen with my wife who is iOS and I am on android.

**Comment by ethylmorphine** [comment]
The bug with png’s is present. Android to iOS or iOS to iOS, whatever, png’s do not render.

**Comment by m0urs** [comment]
Same here with jpgs sent from Android to iOS. Since a few days now. Could this be because of this change in last version “Show generic file icon when encountering image with large dimensions “?

**Comment by michaelkirk-signal** [comment]
Version 2.29.2, released last week, should fix this. Could you make sure you’re on that version?

**Comment by m0urs** [comment]
Ah. Indeed.  I was still on 2.29.1. With 2.29.2 it seems to work again.  Thanks!

> Am 14.09.2018 um 15:29 schrieb Michael Kirk <notifications@github.com>:
> 
> 2.29.2

**Comment by tomk2** [comment]
<img width="293" alt="screen shot 2018-10-09 at 9 20 45 pm" src="https://user-images.githubusercontent.com/3288775/46713096-62410380-cc09-11e8-9aaa-5a4a6f60647c.png">

@michaelkirk-signal I'm still having this issue. Copying an image from Tumblr app and pasting it into Signal gets attached instead of shown inline. Like I said. If I save the image to Photos and insert it from photos (local storage) then it works fine. Pasting from memory just doesn't work. 

I though iOS 12 or newer version would fix it, but hasn't. My current versions:
iOS 12.0 (16A355) iPhone 6s Plus
Tumblr v11.8
Signal 2.29.3.3

Also, sharing a link (say from some News app - Bloomberg) I noticed that the http link isn't on a separate line. Pasting in other apps it is. In iOS11.x copying any article from News app used to have a title and a link and pasting that into the chatbox in signal ended up being concatenated. Meaning no space in front of the http. I have an old screenshot. Looks like some newlines aren't being handled properly.  iOS12 News app only copies the http so it's not an issue when I use that app. But still http isn't on it's own line from other apps. Seems like a related pasting issue.  
<img width="246" alt="screen shot 2018-10-09 at 9 29 44 pm" src="https://user-images.githubusercontent.com/3288775/46713279-75a09e80-cc0a-11e8-9bdb-6bd876cb4477.png">

Any other cases where a .png would be attached instead of being rendered inline?

**Comment by michaelkirk-signal** [comment]
Can you provide a problematic file? Or is it only possible to reproduce when copied directly from tumblr?

Is it every PNG that's copied or just certain ones?

What's the resolution of the image that's failing to paste?

**Comment by tomk2** [comment]
@michaelkirk-signal it's only reproducible when copying directly from Tumblr. Every image (.png) I try to copy and paste. I'm not sure about the sizes, but they vary and behave the same. When I paste it in that textbox the preview looks fine (full screen with a textbox below to type something), but when I click send then it's attached like in the screenshot I provided and any text from the textbox gets discarded. 

However, copying and pasting animated gifs from tumbrl are shown correctly inline and animate fine.

**Comment by tzs1** [comment]
This bug is not happening again for me.

**Comment by richlv** [comment]
Is this still happening for somebody?
