### ISSUE TITLE
Thumbnail scroll view in multiple image message doesn't scroll forward

### ISSUE THREAD

**Issue by raghul-selvaraj-sj** [signalapp/Signal-iOS#4131]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When viewing an image from multiple image group, the thumbnail scrolling available to move between images doesn't scroll backwards from the currently selected image.

### Steps to reproduce
- Send a multiple image message with 10 or more images.
- Now open an image in the multiple-image message(enlarged view)
- Scroll to the last image and select to view it
- Now the thumbnail scroll bar won't move backward(you can't  move to select the initial images)

**Actual result:** Not able to move the thumbnail scroll bar to view previous images

**Expected result:** The thumbnail scroll bar should be free to move irrespective of the currently selected image position

### Screenshots

![test_2](https://user-images.githubusercontent.com/20701077/52831191-bd27c180-30f9-11e9-954e-b49b9269fb54.jpeg)

### Device info

**Device**: iPhone 8 Plus

**iOS version**: iOS 12.1.4

**Signal version:** 2.36.0.6

**Comment by u32i64** [comment]
#### Reproducible on:

**Device**: iPhone 6 Plus
**iOS version**: iOS 12.3 Public beta 5
**Signal version**: 2.39.0.13

#### But:

> with 10 or more images.

This is not required, just `> 1` images in a message.

**The thumbnail scrolling works normally unless one of the last 3 images is selected.**

**Comment by denver-s** [comment]
Not reproducible for me. I think this has been fixed.

**Comment by Raghul-S-1994** [comment]
Still reproducible in Signal 2.41.1.0

**Comment by denver-s** [comment]
I cannot reproduce (version 3.1.0.13)

**Comment by Raghul-S-1994** [comment]
@denver-s I can still reproduce it in v3.1.0.17(beta). The thumbnail scroll works fine while in send window. But on trying to scroll through the thumbnail scroll in received or sent window it doesn't move freely.

**Comment by denver-s** [comment]
I tried again and I can do it. I sent 10 photos, opened one and scrolled (swiped) to the left and right and it works perfectly.

**Comment by raghul-selvaraj-sj** [comment]
This issue is still reproducible.
