### ISSUE TITLE
duplicate contacts shown when composing message

### ISSUE THREAD

**Issue by leecolleton** [signalapp/Signal-iOS#4540]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Duplicate contacts shown when composing a new message

### Steps to reproduce
- select new message icon
- type name of contact

**Actual result:** two identical contacts shown

**Expected result:** only one contact should be shown for each match

### Device info

**Device**: iPod Touch PKJ02LL/A

**iOS version**: 12.4.8

**Signal version:** 3.15.0.23

### Link to debug log

https://debuglogs.org/cb4066075643ef76c5d6e28ea8535dc382d27f77b8935a2aa330fe357e09d0b2.zip

**Comment by leecolleton** [comment]
![IMG_2888](https://user-images.githubusercontent.com/1278011/91928936-234f4780-ec92-11ea-918d-54bf251bee4b.PNG)

**Comment by rb81** [comment]
**+1**

I'm facing the same issue when using the search field on the home screen. This appears to occur only when searching for contacts not already in conversation. Compose window search seems to be okay for me.

(iPhone SE 2nd Gen, iOS 14.2, Signal 5.3.0.16)

**Comment by RichyRich686** [comment]
I am having the same issue. Is there a way to fix it? Please help me

**Comment by philoupd** [comment]
I am facing it the exact same way as @rb81 dose when using the search field.

Using Signal 5.6.0.12 on iOS 14.5 (iPhone 12 Pro)

**Comment by rb81** [comment]
This seems to resolved in 5.6.0.14 on iOS.

**Comment by philoupd** [comment]
5.6.0.14 doesn't appear in the beta branch. I just updated to 5.7.0.7 (beta) and stille have the issue.

**Comment by M00nD3v** [comment]
I am getting two entries for every country, too. Even those, which I already have initiated a conversation with.

**Comment by philoupd** [comment]
The bug still exists in 5.8.0.23

**Comment by robiecz** [comment]
The bug still exists in 5.10.0.49 (iPhone 11 pro, iOS 14.5).

**Comment by philoupd** [comment]
> 

seems to be fixed for me in 5.33.026 (maybe already before)
