### ISSUE TITLE
ProRaw images not handled correctly

### ISSUE THREAD

**Issue by schmeat** [signalapp/Signal-iOS#5337]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Signal is not handling pro raw images correctly. It is being treated like a file. 

There seems to be some amount of time that passes, or a trigger that causes it to eventually work. 

What I am suspecting is that iOS creates a thumbnail or cached version eventually, which signal is then able to pick up and process. 

Also referenced in #4928 but that issue was closed with explanation. 

### Steps to reproduce

1. Enable proraw mode on iPhone camera (requires a pro device)
2. Take a picture
3. Attempt to attach picture in signal chat

**Actual result:**

Attaches it like a file 

**Expected result:**

Attach like a picture 

### Screenshots

![image](https://user-images.githubusercontent.com/1139817/166415841-acb2478d-5257-465f-bf7a-11a553e2978a.jpeg)

### Device info

**Device**: 13 pro max

**iOS version**:

15.4.2

**Signal version:** 

5.37.0.4

### Link to debug log

https://debuglogs.org/ios/5.37.0/caa722567ee33e2b41b95784023ae9eac4e9a7d90a5f4ec07dffd6e7d5815569.zip

**Comment by darrengillman** [comment]
Unable to replicate on iPhone 12 Pro.  Attaching a RAW image (confirmed in Photos as RAW) results in a .jpeg file being added to the message.
**Signal** 5.44.0.10, 
**iOS** 15.6 Beta

**Comment by schmeat** [comment]
@darrengillman How are you attaching it to the conversation? Take a photo in raw mode then immediately try to attach it, without viewing it first. 

I can still consistently replicate it.

![IMG_3980](https://user-images.githubusercontent.com/1139817/179430015-9ddde982-d1cf-4abf-a353-35d285591296.jpg)

https://debuglogs.org/ios/5.46.0/cbc68045dc8fc62f5aac1fac8461429a7ee382105521e360af6fdc79eee27d7b.zip

Signal 5.46.0.10
iOS 15.5

**Comment by schmeat** [comment]
It’s still an issue in the latest beta and should not be marked as stale.

**Comment by armw4** [comment]
Ahhgggggg

Include <pthread>

Plethora #

**Comment by schmeat** [comment]
Really cool how no devs commented on this issue at all, then it gets closed for inactivity.

**Comment by darrengillman** [comment]
Ok, can replicate the issue:
Steps

- phone into raw mode
- Take photo
- Close photos without viewing image
- Click + in signal to add attachment and select from presented images. 

Note: This prev hadn’t worked.  Photo library is not set to store originals on phone (don’t make a phone big enough) so I suspect it was moving the raw image to the cloud and holding a HEIC placeholder on the phone which was then being picked up by signal.

**Comment by rapulum** [comment]
I still have the problem on iPhone 15 Pro. 

![IMG_9087](https://github.com/signalapp/Signal-iOS/assets/98689925/5d07a587-35be-408a-b3c6-f8ceb060b091)

**Comment by schmeat** [comment]
@rapulum yeah this issue will not be fixed, let alone acknowledged unfortunately. I use an iOS shortcut to to convert to JPEGs in the share sheet, either that or use a more supported IM.

**Comment by punkeel** [comment]
Can confirm this is still an issue. Can we reopen this ticket?

**Comment by LorbusChris** [comment]
I'm also experiencing this issue.

@elaine-signal @max-signal @harry-signal @sashaweiss-signal, apologies for the ping, but mind re-opening?

**Comment by chenein** [comment]
Same. Very frustrating that issue has not been acknowledged / addressed.

**Comment by jaydizz** [comment]
This issue still persists. 
I noticed, that it happens very frequently with freshly taken photos. If you take a photo, open it in the Fotos app and wait for 20 seconds, it seems to work fine afterwards. 
My theory is, that in some cases, the JPG has not yet been generated and Signal fails to notice this and does not trigger a conversion. 

Please re-open this issue.

**Comment by janfelixvs** [comment]
Still doesn't work correctly. This problem is nearly 3 years old...

**Comment by iceton** [comment]
![image](https://github.com/user-attachments/assets/55c8e6d2-b22e-4b6c-9f30-dbcefc98d015)

Still a sporadic issue, whether selected in quick carousel, photo selector, or shared from image app. Restarting app does not help.

**Comment by iceton** [comment]
> I'm also experiencing this issue.
> 
> 
> 
> @elaine-signal @max-signal @harry-signal @sashaweiss-signal, apologies for the ping, but mind re-opening?

@elaine-signal @max-signal @harry-signal @sashaweiss-signal 

Please reopen this issue! Still an issue, please see above.

**Comment by Ramiu5** [comment]
Just happened to me today - haven't had any problems with Signal for +7 years.

I came to  the conclusion that it depends on picture resolution. Toke some pictures with Samsung G23Ultra;
12MP - Okay
50MP - Okay
200MP - Can't preview or send them

**Comment by rapulum** [comment]
The bug bothers me several times a day and I regularly have to switch to WhatsApp because of it. 
Still relevant on iPhone 16 Pro

**Comment by schmeat** [comment]
Unfortunately I am unable to reopen it, a dev will have to do so (unlikely)

**Comment by Ramiu5** [comment]
The problem seems to have been solved in version 7.41.0 👍

**Comment by schmeat** [comment]
I am still able to reproduce it in 7.57

**Comment by Ramiu5** [comment]
> The problem seems to have been solved in version 7.41.0 👍

I stand corrected; it works so far as you can see the photos in the gallery when you select them, but at soon as they selected, they are a not show nor can you send them.

**Comment by schvenk** [comment]
Seeing this regularly (though not 100% of the time) on iPhone 15 Pro. I was all set to convince more friends to join Signal and now I'm hesitating specifically because of this issue.

**Comment by indiekind** [comment]
Dito. This is driving me crazy and keeps me from using the app more often. Right now I am using a shortcut to convert everything to JPEG before sending.

**Comment by cguess** [comment]
This is happening even worse in iOS26 beta (5 currently) in that the shareable image now never appears, even after some time. 

I may dig into the code but relevant documentation is here. https://developer.apple.com/documentation/photosui/photospickeritem/encodingdisambiguationpolicy

https://developer.apple.com/documentation/photosui/photospicker/init(selection:maxselectioncount:selectionbehavior:matching:preferreditemencoding:label:)

**Comment by ricokoiv** [comment]
Bump. It's still happening on the latest Signal version and on iOS 26. When is this issue going to be fixed?

**Comment by ianrahman** [comment]
PR with proposed fix in https://github.com/signalapp/Signal-iOS/pull/6108

**Comment by metamatt** [comment]
This symptom has been extremely reproducible for me, for recently taken photos and maybe only under mediocre network conditions for me — as said above, there seems to be some trigger for some change where (per image) it’s no longer a problem. Perhaps upload to iCloud is that trigger. I just know I see this pretty often for a photo I just took and want to share, and less so for older photos. I’m really happy to see a fix in progress.

**Comment by TomasTokaMrazek** [comment]
Signal is the only application, that tries to send DNG file. Every other communication app, be it Messenger, WhatsApp, Discord, Instagram or Teams sends converted JPG. I am not entirely sure, that allowing DNG as a photo media type is the solution. I want to send the smaller JPG, not 60 MB DNG. If I would want to send the raw photo, I would send it as file.

**Comment by chenein** [comment]
This issue is worse than ever for me, particularly in the multiple-photo selector. I continuously get "Failed to select attachment." Selecting and posting the pictures individually sometimes works better, but this means I cannot make a multiple-photo post now.

> Signal is the only application, that tries to send DNG file. Every other communication app, be it Messenger, WhatsApp, Discord, Instagram or Teams sends converted JPG. I am not entirely sure, that allowing DNG as a photo media type is the solution. I want to send the smaller JPG, not 60 MB DNG. 

Fully agree

**Comment by iceton** [comment]
Indeed, seems as of ~weeks ago I have to convert every dng to jpg now, whereas waiting in the image selector before selecting photo used to work sometimes.

**Comment by calebruz** [comment]
This would be really cool if they did something about it. Current workarounds are tedious.

**Comment by dumbenis** [comment]
As of 30 September 2025, I am experiencing the same issue on iPhone 16 Pro with iOS 26.1 and Signal v7.80 (1077): When I press the camera icon in the Signal app and take a photo, a preview is displayed in the Signal app. If I press the plus sign and add a photo from my photo library, the Signal app does not show a preview. WhatsApp does not have this issue. I do not use iCloud to synchronise photos. After six weeks, I am fed up with this issue.

**Comment by TomasTokaMrazek** [comment]
> Indeed, seems as of ~weeks ago I have to convert every dng to jpg now, whereas waiting in the image selector before selecting photo used to work sometimes.

It worked sometimes, becuase there was the JPG conversion in a background. Not sure if it was triggered by Signal or if it's some iOS background task, but I verified, that opening up the photo selection and waiting for a minute for example eventually sent JPG instead of DNG. It stopped completely working since iOS 26 or some newest Signal version, I'm not sure when.

**Comment by metamatt** [comment]
A workaround I use that's good enough for some use cases is just to take a screenshot of the displayed photo in the Photos app, then crop the screenshot to be only the photo content, and copy/paste the cropped screenshot (as pixels not ProRAW) in Signal.

**Comment by ianrahman** [comment]
A workaround I prefer is to edit the DNG photo first in the iOS Photos app. Doesn’t have to be significant, or even noticeable, but as long as any sort of image edit is made then iOS will force a re-render and it becomes available as a jpg in Signal. 

Edit: For multiple photos, you can take the edits from the first image and paste them in the Photos app across a whole range of RAW images, and they should all be automatically available as rendered JPEGs after.

**Comment by dumbenis** [comment]
Inconsistent behaviour on iPhone 16 Pro iOS 26.1 with Signal v7.80 (1077). When I press the camera icon in the Signal app and take a photo, a preview is displayed in the Signal app. If I press the plus sign and add a photo from my library, the Signal app does not show a preview.

**Comment by ianrahman** [comment]
> Inconsistent behaviour on iPhone 16 Pro iOS 26.1 with Signal v7.80 (1077). When I press the camera icon in the Signal app and take a photo, a preview is displayed in the Signal app. If I press the plus sign and add a photo from my library, the Signal app does not show a preview.

@dumbenis the camera feature within the Signal app isn’t capturing a RAW image, it’s capturing a JPG. What you describe is consistent with the prior reports of picking RAW images from the photo library and not being able to view them.

**Comment by dumbenis** [comment]
The issue has been resolved in Signal v7.84 (1140) app on the iPhone 16 Pro. I can take a photo and add it later to a Signal message, displaying the content of the photo instead of the DNG.

**Comment by iceton** [comment]
> issue has been resolved in Signal v7.84 (1140) app on the iPhone 16 Pro

Issue persists for me in v7.85 on iPhone 15 Pro.

**Comment by Soviut** [comment]
I've found that if I try to send the file directly by clicking the Photos button without clicking Manage, then selecting a file to send brings up the DNG file transfer.

However, if I click Manage first and add the photo to my managed list and then click the managed photo, it gives me a proper thumbnail preview and sends as expected.

I'm on an iPhone 17 Pro Max, iOS 26.1, Signal 7.85 (1159)

**Comment by TomasTokaMrazek** [comment]
It started to working for me, not sure if iOS update (26.2) or Signal update (7.89). If I took a photo, I can immediately go to Signal, select it while it's blurry, click on it, wait a second or two for processing and send the image. Works just as other apps.

**Comment by sbstnh** [comment]
Issue persists for me as well: v7.91, iOS26.2, iPhone 15 Pro Max

**Comment by chenein** [comment]
There is no improvement for me on this issue. I cannot use the multiple-photos selector, where I repeatedly get "Failed to select attachment" every time.

**Comment by max-signal** [comment]
We fixed this in a5e2eaaa586c41984d39f83861c434190e6a6ca4, which was released in v7.93 about a month ago. I’m going to close this because reports have stopped, but please do let me know if you’re still seeing this on the latest version.
