### ISSUE TITLE
Groups muted to "always" automatically unmute themselves

### ISSUE THREAD

**Issue by Hainish** [signalapp/Signal-iOS#5956]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Groups muted and set to "always" will automatically unumte themselves.  This does not happen when groups are muted for a specific length of time.

### Steps to reproduce
- Go to a group
- Tap on the group name to go into settings for group
- Tap "mute"
- Mute for "always"

**Actual result:** In the list of groups, after a few seconds the mute icon will disappear and the group will not be muted

**Expected result:** The group should be muted until unmuted.

### Device info

**Device**: iPhone 14 Pro

**iOS version**: 18.2.1

**Signal version:** 7.45 (592)  - TestFlight

**Comment by Hainish** [comment]
The notifications badge for the app also includes the number of messages in the (newly unmuted) groups.

**Comment by franswarn** [comment]
Can confirm the exactly the same behavior. When muting the group, in the chat listing the group shows the mute icon for about 2-3 seconds and then automatically it disappears.

### Device Info

**Device:** iPhone 15 Pro

**iOS version:** 18.2

**Signal version:** 7.44

**Comment by Hainish** [comment]
I just noticed this only occurs when I have signal-desktop open at the same time, but this is performed on iOS.

**Comment by micahflee** [comment]
I just reproduced this. With Signal Desktop open, when I set a group to mute always, it unmutes after a few seconds. When I quit Signal Desktop and do it again, it stays muted.

**Comment by neubian** [comment]
Confirmed on 
Android 14, Signal 7.31.1
Windows 10, Signal Desktop 7.40.0 
Windows 10, Signal Desktop Unknown(at other location, but open).

Absolutely maddening.

**Comment by gabefair** [comment]
This seems to be a universal bug. Everyone is reporting it in my chats. All different phones and versions.

**Comment by Hainish** [comment]
Seems fixed as of v7.40.1 (see https://github.com/signalapp/Signal-Desktop/issues/7148)

**Comment by kinvaris** [comment]
Having similar issues on Android 7.31.1

**Comment by AinoL** [comment]
Same issue on

**OS:** iOS 18.3.1 
**Signal version:** 7.45.1 
**Device:** iPhone 14

**Comment by jasontitus** [comment]
Still seeing frequent unmuting of groups that were set to 'Always' running current Mac desktop (7.62.0), iOS client (7.67), and signal-cli (0.13.18).  Haven't figured out the exact combo that causes it, but it is definitely still happening.
